export type TCard = {
    cardId: string,
    dbfId: string,
    name: string,
    cardSet: string,
    type: string,
    faction: string,
    rarity: string,
    cost: number,
    attack: number,
    health: number,
    text: string,
    flavor: string,
    artist: string,
    collectible: boolean,
    elite: boolean,
    playerClass: string,
    howToGetDiamond: string,
    img: string,
    locale: string
};
